spring.datasource.url=jdbc:postgresql://localhost:5432/laguagecarddb
spring.datasource.username=postgres
spring.datasource.password=postgrespw


server.error.include-message=always
server.error.include-binding-errors=always
